config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new

  resources :apidocs, only: [:index]

  namespace :admin do
    resources :system, only: [:index]
    resources :users do
      get :login
      patch :merge
    end
    resources :exports
    resources :data_sets
    resources :districts do
      collection do
        get :bulk
        post :bulk_update
      end
    end
    resources :notices do
      post :analyze
    end
    resources :bulk_uploads
    resources :replies
    resources :snippets
    resources :charges
    resources :charge_variants
    resources :authorizations

    get :system, to: "system#index", as: :system_status
    root to: "users#index"
  end

  namespace :api, constraints: { format: :json } do
    resources :notices do
      member { patch :mail }
    end
    resources :uploads, only: [:create]
  end

  resources :replies
  resources :snippets

  resources :bulk_uploads do
    member { patch :purge }

    collection do
      post :bulk
      post :import
    end
  end

  resources :notices do
    member do
      get :inspect
      get :colors
      get :share
      get :suggest
      get :pdf
      get :retrieve
      patch :forward
      patch :status
      patch :duplicate
      patch :mail
      patch :enable
      patch :disable
      patch :analyze
      patch :purge
      patch :upload
    end

    collection do
      get :dump
      get :stats
      get :map
      post :geocode
      post :bulk
      post :import
    end
  end

  resource :user, except: %i[create new index] do
    member do
      get :studi
      post :generate_export
      patch :confirmation_mail
      patch :signature
      patch :destroy_signature
    end
  end
  # https://github.com/rails/rails/issues/1769#issuecomment-301643924
  resolve("User") { [:user] }

  resources :districts do
    member { get :wegeheld }
  end

  resources :charges, only: %i[index show] do
    collection { get :list }
  end
  resources :exports, only: :index
  resource :sitemap, only: :show

  scope "/p" do
    get "/charge/:token", to: "public#charge", as: :public_charge
    get "/profile/:token", to: "public#profile", as: :public_profile
    get "/winowig/:user_token/:notice_token",
        to: "public#winowig",
        as: :public_winowig,
        defaults: {
          format: :xml,
        }
  end

  scope "/auth" do
    unless Rails.env.production?
      get "/offline_login/:nickname", to: "sessions#offline_login"
    end
    get "/:provider/callback", to: "sessions#create", as: :provider_callback
    delete "/:provider", to: "sessions#disconnect"
    get "/failure", to: "sessions#failure"
    get "/destroy_alias_session",
        to: "sessions#destroy_alias",
        as: :logout_alias
    get "/destroy_session", to: "sessions#destroy", as: :logout
    get "/validation/:token", to: "sessions#validation", as: :validation
    get "/signup", to: "sessions#signup", as: :signup
    get "/ticket", to: "sessions#ticket", as: :ticket
    get "/login", to: "sessions#login", as: :login
    get "/email", to: "sessions#email", as: :email_login
    post "/complete", to: "sessions#complete", as: :complete
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_signup", to: "sessions#email_signup", as: :email_signup
  end

  root "home#index"

  get "/home", to: "home#index", as: :home
  get "/wegeheld", to: "home#wegeheld", as: :wegeheld
  get "/generator", to: "home#generator", as: :generator
  get "/imprint", to: "home#imprint", as: :imprint
  get "/map", to: "home#map", as: :map
  get "/leaderboard", to: "home#leaderboard", as: :leaderboard
  get "/stats", to: "home#stats", as: :stats
  get "/features", to: "home#features", as: :features
  get "/faq", to: "home#faq", as: :faq
  get "/api", to: "home#api", as: :api
  get "/violation", to: "home#violation", as: :violation
  get "/privacy", to: "home#privacy", as: :privacy
  get "/donate", to: "home#donate", as: :donate
  get "/year", to: "home#year", as: :year
  get "/year2022" => redirect("/year?year=2022")
  get "/year2021" => redirect("/year?year=2021")
  get "/year2020" => redirect("/year?year=2020")
  get "/year2019" => redirect("/year?year=2019")

  if Rails.env.development?
    get "/cdn-cgi/image/width=:width,height=:height,fit=:fit,quality=:quality/storage/:key.:extension",
        to: "styleguide#photo"
  end

  get "/styleguide", to: "styleguide#index"

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/ping",
      to: ->(env) { [200, { "Content-Type" => "text/html" }, ["pong"]] }
end

app/models/api/notice.rb
# frozen_string_literal: true

class Api::Notice < Notice
  include Swagger::Blocks

  swagger_schema :Notice do
    key :required, [:token]
    property :token do
      key :type, :string
    end
    property :status do
      key :type, :string
      key :enum, Notice.statuses.keys
    end
    property :street do
      key :type, :string
    end
    property :city do
      key :type, :string
    end
    property :zip do
      key :type, :string
      key :pattern, '^\d{5}$'
    end
    property :latitude do
      key :type, :number
      key :format, :float
    end
    property :longitude do
      key :type, :number
      key :format, :float
    end
    property :registration do
      key :type, :string
    end
    property :brand do
      key :type, :string
      key :enum, Vehicle.brands
    end
    property :color do
      key :type, :string
      key :enum, Vehicle.colors
    end
    property :tbnr do
      key :type, :string
      key :enum, Charge.parking.pluck(:tbnr)
    end
    property :date do
      key :type, :string
      key :format, :"date-time"
    end
    property :duration do
      key :type, :number
      key :format, :int64
      key :enum, Vehicle.durations.map(&:last)
    end
    property :note do
      key :type, :string
    end
    property :created_at do
      key :type, :string
      key :format, :"date-time"
    end
    property :updated_at do
      key :type, :string
      key :format, :"date-time"
    end
    property :sent_at do
      key :type, :string
      key :format, :"date-time"
    end
    Notice.bitfields[:flags].each_key do |it|
      property it do
        key :type, :boolean
        key :default, false
      end
    end
    property :photos do
      key :type, :array
      items do
        key :type, :object
        property :filename do
          key :type, :string
        end
        property :url do
          key :type, :string
        end
      end
    end
  end

  swagger_schema :NoticeInput do
    allOf do
      schema { key :$ref, :Notice }
      schema do
        key :required,
            %i[
              token
              street
              city
              zip
              latitude
              longitude
              registration
              charge
              date
              duration
              severity
              photos
            ]
        property :token do
          key :type, :string
        end
      end
    end
  end
end

app/controllers/admin/notices_controller.rb
module Admin
  class NoticesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Notice.
    #     page(params[:page]).
    #     per(10)
    # end

    def analyze
      notice = Notice.from_param(params[:notice_id])
      notice.analyze!

      redirect_to admin_notice_path(notice), notice: "Analyse wurde gestartet"
    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Notice.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/notices_controller.rb
# frozen_string_literal: true

class Api::NoticesController < Api::ApplicationController
  swagger_path "/notices" do
    operation :get do
      key :summary, "Get all Notices"
      key :description, "Returns a list of notices for the authorized user"
      key :tags, ["notice"]
      response 200 do
        key :description, "notices response"
        schema do
          key :type, :array
          items { key :$ref, :Notice }
        end
      end
      response :default do
        key :description, "unexpected error"
        schema { key :$ref, :Error }
      end
    end
  end

  def index
    render json: current_user.notices.as_api_response(:public_beta)
  end

  swagger_path "/notices" do
    operation :post do
      key :summary, "Create Notice"
      key :description,
          "Creates a new notice, using the signed_id keys from an upload that was created previously as keys to the photos array"
      key :operationId, "addNotice"
      key :tags, ["notice"]
      parameter do
        key :name, :notice
        key :in, :body
        key :description, "Notice to add"
        key :required, true
        schema { key :$ref, :NoticeInput }
      end
      response 201 do
        key :description, "notice response"
        schema { key :$ref, :Notice }
      end
      response :default do
        key :description, "unexpected error"
        schema { key :$ref, :Error }
      end
    end
  end

  def create
    notice = current_user.notices.build(notice_params)
    notice.analyze!

    render json: notice.as_api_response(:public_beta), status: :created
  end

  swagger_path "/notices/{token}" do
    operation :get do
      key :summary, "Get Notice"
      key :description, "Gets a notice for the authorized user"
      key :tags, ["notice"]
      parameter do
        key :name, :token
        key :in, :path
        key :description, "Token of notice"
        key :required, true
        key :type, :string
      end
      response 200 do
        key :description, "notice response"
        schema { key :$ref, :Notice }
      end
      response :default do
        key :description, "unexpected error"
        schema { key :$ref, :Error }
      end
    end
  end

  def show
    render json:
             current_user
               .notices
               .from_param(params[:id])
               .as_api_response(:public_beta)
  end

  swagger_path "/notices/{token}" do
    operation :patch do
      key :summary, "Update Notice"
      key :description, "Updates a notice for the authorized user"
      key :tags, ["notice"]
      parameter do
        key :name, :token
        key :in, :path
        key :description, "Token of notice to update"
        key :required, true
        key :type, :string
      end
      parameter do
        key :name, :notice
        key :in, :body
        key :description, "Notice to update"
        key :required, true
        schema { key :$ref, :NoticeInput }
      end
      response 200 do
        key :description, "notice response"
        schema { key :$ref, :Notice }
      end
      response :default do
        key :description, "unexpected error"
        schema { key :$ref, :Error }
      end
    end
  end

  def update
    notice = current_user.notices.open.from_param(params[:id])
    notice.update!(notice_params)

    render json: notice.as_api_response(:public_beta)
  end

  swagger_path "/notices/{token}" do
    operation :delete do
      key :summary, "Delete Notice"
      key :description, "Deletes a single notice for the authorized user"
      key :tags, ["notice"]
      parameter do
        key :name, :token
        key :in, :path
        key :description, "Token of notice to delete"
        key :required, true
        key :type, :string
      end
      response 200 do
        key :description, "notice response"
        schema { key :$ref, :Notice }
      end
      response :default do
        key :description, "unexpected error"
        schema { key :$ref, :Error }
      end
    end
  end

  def destroy
    notice = current_user.notices.from_param(params[:id])

    notice.destroy!
    head(200)
  end

  swagger_path "/notices/{token}/mail" do
    operation :patch do
      key :summary, "Submit Notice"
      key :description, "Submits a single notice for the authorized user"
      key :tags, ["notice"]
      parameter do
        key :name, :token
        key :in, :path
        key :description, "Token of notice to submit"
        key :required, true
        key :type, :string
      end
      response 200 do
        key :description, "notice response"
        schema { key :$ref, :Notice }
      end
      response :default do
        key :description, "unexpected error"
        schema { key :$ref, :Error }
      end
    end
  end

  def mail
    notice = current_user.notices.from_param(params[:id])
    notice.mark_shared!

    NoticeMailer.charge(notice).deliver_later

    render json: notice.as_api_response(:public_beta)
  end

  private

  def notice_params
    params.require(:notice).permit(
      :charge,
      :date,
      :date_date,
      :date_time,
      :registration,
      :brand,
      :color,
      :street,
      :zip,
      :city,
      :location,
      :latitude,
      :longitude,
      :note,
      :duration,
      :severity,
      :vehicle_empty,
      :hazard_lights,
      :expired_tuv,
      :expired_eco,
      :over_2_8_tons,
      photos: [],
    )
  end
end

app/views/notices/_actions.html.slim
- button_text ||= false
button.btn.btn-default.btn-sm.dropdown-toggle type="button" data-toggle="dropdown"
  | <span class="glyphicon glyphicon-cog"></span>
  =<> 'Aktionen' if button_text
  | <span class="caret"></span>
ul.dropdown-menu
  - if notice.incomplete?
    li
      = link_to edit_notice_path(notice)
        span.glyphicon.glyphicon-edit>
        | Meldung bearbeiten
  - elsif notice.open?
    li
      = link_to share_notice_path(notice)
        span.glyphicon.glyphicon-share>
        | Anzeige erstatten
    li
      = link_to edit_notice_path(notice)
        span.glyphicon.glyphicon-edit>
        | Meldung bearbeiten
    li
      = link_to forward_notice_path(notice), data: {confirm: 'Die Meldung wird an einen anderen Nutzer übertragen'}, method: :patch
        span.glyphicon.glyphicon-forward>
        | Meldung übertragen
    li
      = link_to status_notice_path(notice), data: {confirm: 'Die Meldung wird als gemeldet markiert'}, method: :patch
        span.glyphicon.glyphicon-status-shared>
        span als gemeldet markieren

  li
    = link_to notice_path(notice)
      span.glyphicon.glyphicon-eye-open>
      | Meldung ansehen
  li
    = link_to duplicate_notice_path(notice), data: {confirm: 'Die Meldung wird nun dupliziert'}, method: :patch
      span.glyphicon.glyphicon-duplicate>
      | Meldung duplizieren
  li
    = link_to notice_path(notice), method: :delete, data: {confirm: 'Die Meldung wird endgültig gelöscht'}, title: 'löschen'
      span.glyphicon.glyphicon-trash>
      | Meldung löschen

  - unless notice.incomplete?
    li
      = link_to pdf_notice_path(notice)
        span.glyphicon.glyphicon-save-file>
        | Meldung als PDF
    li
      = link_to(public_winowig_path(current_user.token, notice.token), target: :blank) do
        span.glyphicon.glyphicon-save-file>
        | Meldung als WiNOWiG

  - if notice.disabled?
    li
      = link_to enable_notice_path(notice), data: {confirm: 'Die Meldung ist anschließend wieder öffentlich erreichbar'}, method: :patch
        span.glyphicon.glyphicon-plus-sign>
        | Meldung aktivieren
  - else
    li
      = link_to disable_notice_path(notice), data: {confirm: 'Die Meldung ist anschließend öffentlich nicht mehr erreichbar'}, method: :patch
        span.glyphicon.glyphicon-minus-sign>
        | Meldung deaktivieren
    li
      = link_to public_charge_path(notice)
        span.glyphicon.glyphicon-globe>
        | Anzeige ansehen

app/views/notices/_alerts.html.slim
- photo_doubles = notice.photo_doubles
- if photo_doubles.present?
  .alert.alert-warning.alert-dismissable
    button type="button" class="close" data-dismiss="alert" ×
    .pull-right
      = button_to @notice, method: :delete, class: 'btn btn-xs btn-default', data: {confirm: 'Die Meldung wird endgültig gelöscht'}
        | Meldung löschen

    strong
      | Achtung, du hast schon Fotos mit identischem Namen hochgeladen, falls es OK ist einfach fortfahren:
      - photo_doubles.each do |photo|
        =< link_to photo.filename, photo.record

- date_doubles = notice.date_doubles
- if date_doubles.present?
  .alert.alert-warning.alert-dismissable
    button type="button" class="close" data-dismiss="alert" ×
    .pull-right
      = button_to @notice, method: :delete, class: 'btn btn-xs btn-default', data: {confirm: 'Die Meldung wird endgültig gelöscht'}
        | Meldung löschen

    strong
      | Achtung, du hast schon eine Meldung für dieses Datum mit identischem Nummernschild, falls es OK ist einfach fortfahren:
      - date_doubles.each do |notice|
        =< link_to "Meldung ##{notice.id}", notice

- if notice.date.present? && notice.date < 2.months.ago
  .alert.alert-warning.alert-dismissable
    button type="button" class="close" data-dismiss="alert" ×
    .pull-right
      = button_to @notice, method: :delete, class: 'btn btn-xs btn-default', data: {confirm: 'Die Meldung wird endgültig gelöscht'}
        | Meldung löschen

    strong Achtung, die Verjährungsfrist von Parkvergehen beträgt nur 3 Monate. Es ist fraglich, ob diese Anzeige noch rechtzeitig bearbeitet wird.

- if notice.data_sets.select(&:exif?).blank?
  .alert.alert-info.alert-dismissable
    button type="button" class="close" data-dismiss="alert" ×
    strong Aus den Beweisfotos konnten leider keine EXIF-Metadaten für die automatische Ermittlung von Adresse und Zeitpunkt ausgelesen werden.
  .well.well-sm.callout-primary= render('components/geocoding_hint')

- if notice.distance_too_large?
  .alert.alert-warning.alert-dismissable
    button type="button" class="close" data-dismiss="alert" ×
    strong Achtung, die Koordinaten der Meldung und die des zugeordneten Bezirks liegen mehr als #{Geo::MAX_DISTANCE} km auseinander!

app/views/notices/_picker_modal.html.slim
.modal.fade id="modal_map" tabindex="-1" role="dialog"
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-label="Schließen"
          span aria-hidden="true" &times;
        h4.modal-title Adresse auswählen
      .modal-body
        .well.well-sm.callout-primary Den Marker per Doppel-Click und Drag&Drop positionieren, oder den Button für den aktuellen Standort verwenden, die Adresse wird dann aktualisiert.
        - data = { coordinates: coordinates, street: '#notice_street', zip: '#notice_zip', city: '#notice_city', latitude: '#notice_latitude', longitude: '#notice_longitude', trigger: '#geolocation' }
        = content_tag(:div, id: "map_picker_canvas", class: "map-canvas", data: data) do
          p Enable JS to view Map!

        javascript:
          (function() {
            const picker = new GPickerMap($("#map_picker_canvas"));
            picker.show();
            $('#modal_map').on('shown.bs.modal', () => picker.rerender());
          })();
      .modal-footer
        .btn-group
          = button_tag type: :button, class: "btn btn-default btn-sm", id: 'geolocation' do
            span.glyphicon.glyphicon-map-marker>
            | aktueller Standort
          button type="button" class="btn btn-default btn-sm" data-dismiss="modal"
            span.glyphicon.glyphicon-remove>
            | Schließen

app/views/notices/_reply_list.html.slim
.table-responsive
  table.table.table-striped.table-hover
    thead
      tr
        th= Reply.human_attribute_name(:created_at)
        th= Reply.human_attribute_name(:sender)
        th= Reply.human_attribute_name(:subject)
        th= Reply.human_attribute_name(:content)
    tbody
      - replies.each_with_index do |reply|
        tr
          td(nowrap)= l(reply.created_at, format: :short)
          td= mail_to(reply.sender)
          td= reply.subject
          td= render('reply_modal_button', reply: reply)

app/views/notices/_reply_modal_button.html.slim
button type="button" class="btn btn-sm btn-default" data-toggle="modal" data-target="#modal_#{dom_id(reply)}"
  span.glyphicon.glyphicon-eye-open>
  | Ansehen

.modal.fade id="modal_#{dom_id(reply)}" tabindex="-1" role="dialog"
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        button type="button" class="close" data-dismiss="modal" aria-label="Schließen"
          span aria-hidden="true" &times;
        h4.modal-title= reply.subject
      .modal-body
        = simple_format(reply.content)
      .modal-footer
        .btn-group
          - if reply.action_mailbox_inbound_email.present?
            = link_to(rails_blob_path(reply.action_mailbox_inbound_email.raw_email.blob, disposition: "attachment"), class: 'btn btn-sm btn-default', title: 'herunterladen') do
              span.glyphicon.glyphicon-download>
              | Herunterladen
          button type="button" class="btn btn-sm btn-default" data-dismiss="modal"
            span.glyphicon.glyphicon-remove>
            | Schließen

app/views/notices/_safari_hint.html.slim
.well.well-sm.callout#safari_hint.hidden
  p Für die Erkennung des Standortes auf iOS muss vor dem Aufnehmen von Beweisfotos folgende Einstellung konfiguriert werden:
  <code>Einstellungen > Kamera > Formate > Maximale Kompatibilität</code>


javascript:
  if (!!navigator.userAgent.match(/iphone|ipad/i)) {
    document.getElementById('safari_hint').classList.remove('hidden');
  }

app/views/notices/_snippet_buttons.html.slim
.btn-group.btn-group-xs
  - if notes.present?
    a.text-muted(href="#" class='btn btn-default' onclick="setSnippet(-1); return false;") <
  a.text-muted(href="#" data-toggle="modal" data-target="#modal_snippet" onclick="$('#snippet_content').val($('#notice_note').val()); return false;" class='btn btn-default') +
  a.text-muted(href="#" class='btn btn-default' onclick="$('#notice_note').val(''); return false;") x
  - if notes.present?
    a.text-muted(href="#" class='btn btn-default' onclick="setSnippet(1); return false;") >

javascript:
  var snippetIndex = null;
  var notes = #{notes.to_json.html_safe}
  function setSnippet(direction) {
    if (snippetIndex === null) {
      snippetIndex = direction > 0 ? 0 : notes.length - 1;
    } else {
      snippetIndex += direction;
      if (snippetIndex >= notes.length) {
        snippetIndex = 0;
      } else if (snippetIndex < 0) {
        snippetIndex = notes.length - 1;
      }
    }
    $('#notice_note').val(notes[snippetIndex]);
  }

app/views/notices/_snippet_modal.html.slim
.modal.fade id="modal_snippet" tabindex="-1" role="dialog"
  = form_for(Snippet.new(user: current_user), remote: true) do |form|
    .modal-dialog.modal-lg
      .modal-content
        .modal-header
          button type="button" class="close" data-dismiss="modal" aria-label="Schließen"
            span aria-hidden="true" &times;
          h4.modal-title Vorlage speichern
        .modal-body
          = render('snippets/form_inputs', form:)
        .modal-footer
          .btn-group
            = form.submit "Vorlage speichern", class: "btn btn-sm btn-success"
            button type="button" class="btn btn-default btn-sm" data-dismiss="modal"
              span.glyphicon.glyphicon-remove>
              | Schließen

app/views/notices/purge.js.erb
$("#photo_modal_<%= params[:photo_id] %>").modal('toggle');
$("#photo_item_<%= params[:photo_id] %>").hide();

app/views/notices/share.html.slim
- set_title 'Anzeige erstatten'

= render 'three_step', step: :third

- if @district.blank?
    .alert.alert-warning
      .pull-right
        = button_to('Neuen Bezirk erfassen', districts_path, class: 'btn btn-xs btn-default', params: {district: {name: @notice.city, zip: @notice.zip, prefixes: ''}})
      strong
        | Ein Bezirk für die PLZ #{@notice.zip} ist noch nicht hinterlegt! Füge diesen hinzu, falls Du die E-Mail-Adresse der zuständigen Stelle kennst.

- else
  .well.well-sm.callout-primary Kontrolliere die erfassten Informationen und Beweisfotos in der Vorschau. Danach kann die Anzeige direkt per E-Mail erstattet werden.

  .row
    .col-lg-12
      pre.charge
        = @mail.text_part.decoded
      = render 'components/photos', notice: @notice, publicly: true

  hr.spacer

  = render 'alerts', notice: @notice

  = form_errors @notice
  = form_for @notice, url: mail_notice_path(@notice), method: :patch do |form|

    - if @notice.district.munich?
      .alert.alert-info
        strong
          |
            In München sind ausserhalb des Mittleren Rings die örtlichen #{link_to 'Polizei-Inspektionen', 'https://www.polizei.bayern.de/?uigmd=münchen&gdts=162000001&gmds=162000&gmdklartext=80331%20München', target: '_blank'}
            anstelle des #{link_to 'KVR', 'http://www.muenchen.de/dienstleistungsfinder/muenchen/1073669/', target: '_blank'} zuständig,
            deren Zuständigkeit man auf #{link_to 'dieser Karte', 'https://umap.openstreetmap.fr/de/map/unbenannte-karte_422905#14/48.1444/11.5718', target: '_blank'} findet.
    - elsif @notice.district.signature?
      - if current_user.signature.present?
        .alert.alert-info
          strong
            | Für den Bezirk #{@notice.district.display_name} werden Anzeigen per PDF mit Unterschrift übermittelt.
      - else
        .alert.alert-info
          strong
            | Für den Bezirk #{@notice.district.display_name} sollte #{link_to 'im Profil', edit_user_path(anchor: :signature)} eine Unterschrift für das Versenden der Anzeige als PDF hinterlegt sein!
    - elsif @notice.district.aliases.present?
      .alert.alert-info
        strong
          | Für den Bezirk #{@notice.district.zip} liegen alternative E-Mail-Adressen vor.

    .row
      .col-lg-8
        = render 'callout', section: 'notices', key: 'send_email'

        .form-group
          = form.label :district, class: "control-label control-label-required"
          - if @notice.district.aliases.present?
            = select_tag :send_to, options_for_email(@notice.district, @notice.point), {include_blank: 'E-Mail Auswählen', class: "form-control", required: true }
            - if @notice.district.munich?
              = hint do
                | Die E-Mail-Adresse der zuständigen PI wurde anhand des Standortes vorausgewählt.
            - else
              = hint do
                | Für diesen Bezirk sind mehrere E-Mail-Adressen hinterlegt.
          - else
            = form.text_field :district, value: "#{form.object.district.email} (#{form.object.district.display_name})", disabled: true, class: "form-control"
            = hint do
              | Die E-Mail-Adresse der zuständigen Stelle wurde anhand der Postleitzahl ermittelt. #{link_to 'Adresse stimmt nicht', edit_district_path(@notice.district)}?

          - if @notice.district.winowig?
            .well.well-sm.callout-primary Mit der Stadt Dresden nutzen wir eine XML basierte Schnittstelle zur dort genutzten Software #{link_to 'WiNOWiG', 'https://www.owig.de/'}.
          - elsif @notice.district.hamburg?
              / no PDF in hamburg /
          - else
            .form-group
              .checkbox
                = label_tag :send_via_pdf
                  = check_box_tag :send_via_pdf, '', @notice.district.signature?
                  | Anzeige per PDF-Anhang versenden
              = hint do
                | Durch das Versenden per PDF-Anhang wird die Meldung als PDF generiert und ggf. die #{link_to 'im Profil', edit_user_path(anchor: :signature)} hinterlegte Unterschrift mit eingefügt.

      .col-lg-4
        = render("components/map/single", notice: @notice, kind: :private, css_class: 'mini-map-canvas')


    hr.spacer

    .row
      .col-lg-12
        .pull-right
          .btn-group
            .btn-group
              .dropdown
                button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown"
                  | <span class="glyphicon glyphicon-cog"></span> Aktionen <span class="caret"></span>
                ul.dropdown-menu
                  li
                    = link_to edit_notice_path(@notice)
                      span.glyphicon.glyphicon-edit>
                      | Meldung bearbeiten
                  li
                    = link_to pdf_notice_path(@notice)
                      span.glyphicon.glyphicon-save-file>
                      | Meldung als PDF
                  li
                    = link_to forward_notice_path(@notice), data: {confirm: 'Die Meldung wird an einen anderen Nutzer übertragen'}, method: :patch
                      span.glyphicon.glyphicon-forward>
                      | Meldung übertragen
                  li
                    = link_to public_charge_path(@notice)
                      span.glyphicon.glyphicon-globe>
                      | Anzeige ansehen
            = form.submit 'Anzeige erstatten', class: "btn btn-success", disabled: @notice.district.blank?

app/views/notices/show.html.slim
- set_title "#{@notice.registration} #{@notice.tbnr}", t('navigation.notices')

.panel.panel-default
  .panel-heading
    .row
      .col-xs-8
        .dropdown
          = render('actions', notice: @notice, button_text: true)
      .col-xs-4.text-right

  .panel-body
    .row
      .col-lg-6
        = render('components/details', notice: @notice)
      .col-lg-6
        = render('components/photos', notice: @notice, publicly: true)
  - if @notice.replies.present?
    = render('reply_list', replies: @notice.replies)
  - if @notice.coordinates?
    .panel-body.panel-body-map
      = render("components/map/single", notice: @notice, kind: :private)