config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new

  resources :apidocs, only: [:index]

  namespace :admin do
    resources :system, only: [:index]
    resources :users do
      get :login
      patch :merge
    end
    resources :exports
    resources :data_sets
    resources :districts do
      collection do
        get :bulk
        post :bulk_update
      end
    end
    resources :notices do
      post :analyze
    end
    resources :bulk_uploads
    resources :replies
    resources :snippets
    resources :charges
    resources :charge_variants
    resources :authorizations

    get :system, to: "system#index", as: :system_status
    root to: "users#index"
  end

  namespace :api, constraints: { format: :json } do
    resources :notices do
      member { patch :mail }
    end
    resources :uploads, only: [:create]
  end

  resources :replies
  resources :snippets

  resources :bulk_uploads do
    member { patch :purge }

    collection do
      post :bulk
      post :import
    end
  end

  resources :notices do
    member do
      get :inspect
      get :colors
      get :share
      get :suggest
      get :pdf
      get :retrieve
      patch :forward
      patch :status
      patch :duplicate
      patch :mail
      patch :enable
      patch :disable
      patch :analyze
      patch :purge
      patch :upload
    end

    collection do
      get :dump
      get :stats
      get :map
      post :geocode
      post :bulk
      post :import
    end
  end

  resource :user, except: %i[create new index] do
    member do
      get :studi
      post :generate_export
      patch :confirmation_mail
      patch :signature
      patch :destroy_signature
    end
  end
  # https://github.com/rails/rails/issues/1769#issuecomment-301643924
  resolve("User") { [:user] }

  resources :districts do
    member { get :wegeheld }
  end

  resources :charges, only: %i[index show] do
    collection { get :list }
  end
  resources :exports, only: :index
  resource :sitemap, only: :show

  scope "/p" do
    get "/charge/:token", to: "public#charge", as: :public_charge
    get "/profile/:token", to: "public#profile", as: :public_profile
    get "/winowig/:user_token/:notice_token",
        to: "public#winowig",
        as: :public_winowig,
        defaults: {
          format: :xml,
        }
  end

  scope "/auth" do
    unless Rails.env.production?
      get "/offline_login/:nickname", to: "sessions#offline_login"
    end
    get "/:provider/callback", to: "sessions#create", as: :provider_callback
    delete "/:provider", to: "sessions#disconnect"
    get "/failure", to: "sessions#failure"
    get "/destroy_alias_session",
        to: "sessions#destroy_alias",
        as: :logout_alias
    get "/destroy_session", to: "sessions#destroy", as: :logout
    get "/validation/:token", to: "sessions#validation", as: :validation
    get "/signup", to: "sessions#signup", as: :signup
    get "/ticket", to: "sessions#ticket", as: :ticket
    get "/login", to: "sessions#login", as: :login
    get "/email", to: "sessions#email", as: :email_login
    post "/complete", to: "sessions#complete", as: :complete
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_signup", to: "sessions#email_signup", as: :email_signup
  end

  root "home#index"

  get "/home", to: "home#index", as: :home
  get "/wegeheld", to: "home#wegeheld", as: :wegeheld
  get "/generator", to: "home#generator", as: :generator
  get "/imprint", to: "home#imprint", as: :imprint
  get "/map", to: "home#map", as: :map
  get "/leaderboard", to: "home#leaderboard", as: :leaderboard
  get "/stats", to: "home#stats", as: :stats
  get "/features", to: "home#features", as: :features
  get "/faq", to: "home#faq", as: :faq
  get "/api", to: "home#api", as: :api
  get "/violation", to: "home#violation", as: :violation
  get "/privacy", to: "home#privacy", as: :privacy
  get "/donate", to: "home#donate", as: :donate
  get "/year", to: "home#year", as: :year
  get "/year2022" => redirect("/year?year=2022")
  get "/year2021" => redirect("/year?year=2021")
  get "/year2020" => redirect("/year?year=2020")
  get "/year2019" => redirect("/year?year=2019")

  if Rails.env.development?
    get "/cdn-cgi/image/width=:width,height=:height,fit=:fit,quality=:quality/storage/:key.:extension",
        to: "styleguide#photo"
  end

  get "/styleguide", to: "styleguide#index"

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/ping",
      to: ->(env) { [200, { "Content-Type" => "text/html" }, ["pong"]] }
end

app/models/bulk_upload.rb
# frozen_string_literal: true

class BulkUpload < ApplicationRecord
  belongs_to :user
  has_many :notices, dependent: :nullify
  has_many_attached :photos

  enum status: {
    initial: 0,
    processing: 1,
    open: 2,
    done: 3,
    importing: 4,
    error: -99,
  }

  validates :photos,
            presence: true,
            unless: -> { done? || importing? || error? }
  validates :shared_album_url, presence: true, if: -> { importing? }

  def self.for_reminder
    open
      .joins(:user)
      .where(
        created_at: [(21.days.ago.beginning_of_day)..(14.days.ago.end_of_day)],
      )
      .merge(User.not_disable_reminders)
      .merge(User.active)
  end

  def purge_photo!(photo_id)
    photos.find(photo_id).purge_later

    update!(status: :done) if photos.blank?
  end
end

app/controllers/admin/bulk_uploads_controller.rb
module Admin
  class BulkUploadsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = BulkUpload.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   BulkUpload.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/bulk_uploads_controller.rb
# frozen_string_literal: true

class BulkUploadsController < ApplicationController
  before_action :authenticate!

  def index
    @table_params = {}

    @bulk_uploads =
      current_user.bulk_uploads.with_attached_photos.page(params[:page])

    filter = params[:filter]
    if filter.present?
      @table_params[:filter] = filter.to_unsafe_hash
      @bulk_uploads = @bulk_uploads.where(status: filter[:status]) if filter[
        :status
      ].present?
    end

    order = params[:order]
    if order.present?
      @table_params[:order] = order.to_unsafe_hash
      if order[:column].present? && order[:value].present?
        @bulk_uploads = @bulk_uploads.reorder(order[:column] => order[:value])
      end
    end
  end

  def show
    @bulk_upload = current_user.bulk_uploads.find(params[:id])
  end

  def new
    @bulk_upload = current_user.bulk_uploads.build
  end

  def create
    bulk_upload = current_user.bulk_uploads.create(bulk_upload_params)

    redirect_to edit_bulk_upload_path(bulk_upload),
                notice: "Massen-Upload wurde angelegt"
  end

  def edit
    session[:bulk_upload_order_column] = @order_column =
      params[:order_column] || session[:bulk_upload_order_column] || "filename"
    session[:bulk_upload_order_direction] = @order_direction =
      params[:order_direction] || session[:bulk_upload_order_direction] || "asc"

    @bulk_upload = current_user.bulk_uploads.find(params[:id])
    case @order_column
    when "filename"
      @photos =
        @bulk_upload
          .photos
          .includes(:blob)
          .references(:blob)
          .order("active_storage_blobs.filename" => @order_direction)
    else
      @photos =
        @bulk_upload
          .photos
          .includes(:blob)
          .references(:blob)
          .order("active_storage_blobs.created_at" => @order_direction)
    end
  end

  def update
    bulk_upload =
      current_user.bulk_uploads.with_attached_photos.find(params[:id])

    if params[:one_per_photo]
      photos = bulk_upload.photos
      photos.each do |photo|
        notice = current_user.notices.build(bulk_upload:)
        Notice.transaction do
          notice.save_incomplete!
          photo.update!(record: notice)
        end
        notice.analyze!
      end
      bulk_upload.update! status: :done

      redirect_to edit_bulk_upload_path(bulk_upload),
                  notice: "Neue Meldungen wurden erzeugt"
    elsif params[:bulk_upload]
      photos = bulk_upload.photos.find(bulk_upload_update_photo_ids)
      notice = current_user.notices.build(bulk_upload:)
      Notice.transaction do
        notice.save_incomplete!
        photos.compact.each { |photo| photo.update!(record: notice) }
      end
      notice.analyze!

      if bulk_upload.reload.photos.present?
        redirect_to edit_bulk_upload_path(bulk_upload),
                    notice: "Neue Meldung aus Fotos erzeugt"
      else
        bulk_upload.update! status: :done

        redirect_to edit_bulk_upload_path(bulk_upload),
                    notice:
                      "Neue Meldung aus Fotos erzeugt, der Massen-Upload wurde vollständig zugeordnet"
      end
    else
      redirect_to edit_bulk_upload_path(bulk_upload),
                  alert: "Es wurde kein Foto ausgewählt"
    end
  end

  def purge
    bulk_upload = current_user.bulk_uploads.find(params[:id])
    bulk_upload.purge_photo!(params[:photo_id])

    respond_to do |format|
      format.js { render(layout: false) }
      format.html do
        redirect_back(
          fallback_location: edit_bulk_upload_path(bulk_upload),
          notice: "Foto gelöscht",
        )
      end
    end
  end

  def destroy
    bulk_upload = current_user.bulk_uploads.find(params[:id])
    bulk_upload.destroy!

    redirect_to bulk_uploads_path, notice: "Massen-Upload wurde gelöscht"
  end

  def bulk
    action = params[:bulk_action] || "destroy"
    bulk_uploads = current_user.bulk_uploads.where(id: params[:selected])
    case action
    when "destroy"
      bulk_uploads.destroy_all
      flash[:notice] = "Die Massen-Uploads wurden gelöscht"
    end

    redirect_to bulk_uploads_path
  end

  def import
    bulk_upload = current_user.bulk_uploads.create(bulk_upload_import_params)
    bulk_upload.status = :importing
    bulk_upload.save!
    PhotosDownloadJob.perform_later(bulk_upload)

    redirect_to edit_bulk_upload_path(bulk_upload),
                notice:
                  "Massen-Upload wurde angelegt, Beweisfotos werden importiert"
  end

  private

  def bulk_upload_update_photo_ids
    params.require(:bulk_upload).require(:photos)
  end

  def bulk_upload_params
    params.require(:bulk_upload).permit(photos: [])
  end

  def bulk_upload_import_params
    params.require(:bulk_upload).permit(:shared_album_url)
  end
end

app/views/bulk_uploads/_actions.html.slim
.flex-buttons.btn-group.btn-group-sm
  = link_to bulk_upload_path(bulk_upload), class: 'btn btn-primary', title: 'ansehen'
    span.glyphicon.glyphicon-eye-open
  = link_to edit_bulk_upload_path(bulk_upload), class: 'btn btn-primary', title: 'bearbeiten'
    span.glyphicon.glyphicon-edit
  = link_to bulk_upload_path(bulk_upload), method: :delete, remote: true, data: {confirm: 'Der Upload wird entgültig gelöscht'}, class: 'btn btn-primary', title: 'löschen'
    span.glyphicon.glyphicon-trash

app/views/bulk_uploads/_bulk_upload_actions.html.slim
- button_text ||= false
button.btn.btn-default.btn-sm.dropdown-toggle type="button" data-toggle="dropdown"
  | <span class="glyphicon glyphicon-cog"></span>
  =<> 'Aktionen' if button_text
  | <span class="caret"></span>
ul.dropdown-menu
  - if bulk_upload.photos.present?
    li
      = link_to edit_bulk_upload_path(bulk_upload)
        span.glyphicon.glyphicon-move>
        | Massen-Upload gruppieren
  li
    = link_to bulk_upload_path(bulk_upload)
      span.glyphicon.glyphicon-eye-open>
      | Massen-Upload ansehen
  li
    = link_to bulk_upload_path(bulk_upload), method: :delete, data: {confirm: 'Der Upload wird endgültig gelöscht'}
      span.glyphicon.glyphicon-trash>
      | Massen-Upload löschen

app/views/bulk_uploads/_bulk_upload_status.html.slim
- legend ||= false
- legend_text = t(status, scope: 'bulk_uploads.status-hints', default: '')
span.label.label-default(class="label-status-#{status}" title=legend_text)
  span.glyphicon(class="glyphicon-status-#{status}")
  span<= t(status, scope: 'bulk_uploads.status')
- if legend && legend_text.present?
  small<= legend_text

app/views/bulk_uploads/_jobs_hint.html.slim
- sidekiq_stats = Sidekiq::Stats.new
- if sidekiq_stats.enqueued.positive?
  .alert.alert-info
    strong Derzeit werden im Hintergrund #{sidekiq_stats.enqueued} Aufgaben von #{sidekiq_stats.processes_size} Prozessen verarbeitet und die Wartezeit beträgt #{distance_of_time_in_words(sidekiq_stats.default_queue_latency)}.

app/views/bulk_uploads/_notice_list.html.slim
.table-responsive
  table.table.table-striped.table-hover
    thead
      tr
        th
        th= Notice.human_attribute_name(:registration)
        th= Notice.human_attribute_name(:created_at)
        th= Notice.human_attribute_name(:date)
        th= Notice.human_attribute_name(:status)
    tbody
      - notices.each do |notice|
        tr
          td.text-center
            = link_to(notice)
              - notice.photos.first(1).each do |photo|
                = image_tag(url_for_photo(photo, size: :preview), class: 'index-photo')
          td
            = link_to_notice(notice) do
              - if notice.incomplete?
                = render 'status', status: :incomplete
              - else
                = registration_label(notice.registration)
          td(nowrap)
            = link_to_notice(notice) do
              = d(notice.created_at)
          td(nowrap)
            = link_to_notice(notice) do
              = d(notice.date, default: '-')
          td= render 'status', status: notice.status

app/views/bulk_uploads/_photo_list.html.slim
.well.well-sm.clearfix(ondragover="ablegenErlauben(event, this)" ondragleave="ablegenLeave(event, this)" ondragenter="ablegenEnter(event, this)" ondrop="ablegen(event, this)")
  ul.photo-list.droppable-list
    - photos.each_with_index do |photo, index|
      li.list-item(draggable="true" id="photo_item_#{photo.id}" ondragstart="ziehen(event)")
        .panel
          a(href="#" data-toggle="modal" data-target="#photo_modal_#{photo.id}" draggable="false")
            = image_tag(url_for_photo(photo, size: :preview), class: 'item-photo', draggable: 'false')
            = hidden_field_tag('bulk_upload[photos][]', photo.id, id: "photo_input_#{photo.id}")
          .btn-group-vertical
            button type="button" class="btn btn-default btn-s" data-toggle="modal" data-target="#photo_modal_#{photo.id}" title="ansehen"
              span.glyphicon.glyphicon-eye-open
            button type="button" class="btn btn-default btn-s" onclick="ablegenMove('photo_item_#{photo.id}')" title="zuordnen"
              span.glyphicon.glyphicon-move

        .modal.fade id="photo_modal_#{photo.id}" tabindex="-1" role="dialog"
          .modal-dialog.modal-lg
            .modal-content
              .modal-header
                button type="button" class="close" data-dismiss="modal" aria-label="Schließen"
                  span aria-hidden="true" &times;
                h4.modal-title Beweisfoto ##{index + 1}
              .modal-body
                = render('components/photo_zoom', photo: photo)
              .modal-footer
                .btn-group
                  = link_to(purge_bulk_upload_path(bulk_upload, photo_id: photo.id), method: :patch, data: {confirm: t('notices.confirm')}, class: 'btn btn-sm btn-default', title: 'löschen', remote: true) do
                    span.glyphicon.glyphicon-trash>
                    | Löschen
                  = link_to(rails_blob_path(photo, disposition: "attachment"), class: 'btn btn-sm btn-default', title: 'herunterladen') do
                    span.glyphicon.glyphicon-download>
                    | Herunterladen
                  button type="button" class="btn btn-sm btn-default" data-dismiss="modal"
                    span.glyphicon.glyphicon-remove>
                    | Schließen

app/views/bulk_uploads/_upload_actions.html.slim
- button_text ||= false
button.btn.btn-default.btn-sm.dropdown-toggle type="button" data-toggle="dropdown"
  | <span class="glyphicon glyphicon-cog"></span>
  =<> 'Aktionen' if button_text
  | <span class="caret"></span>
ul.dropdown-menu
  - if bulk_upload.photos.present?
    li
      = link_to edit_bulk_upload_path(bulk_upload)
        span.glyphicon.glyphicon-move>
        | Massen-Upload gruppieren
  li
    = link_to bulk_upload_path(bulk_upload)
      span.glyphicon.glyphicon-eye-open>
      | Massen-Upload ansehen
  li
    = link_to bulk_upload_path(bulk_upload), method: :delete, data: {confirm: 'Der Upload wird endgültig gelöscht'}
      span.glyphicon.glyphicon-trash>
      | Massen-Upload löschen

app/views/bulk_uploads/_upload_status.html.slim
- legend ||= false
- legend_text = t(status, scope: 'bulk_uploads.status-hints', default: '')
span.label.label-default(class="label-status-#{status}" title=legend_text)
  span.glyphicon(class="glyphicon-status-#{status}")
  span<= t(status, scope: 'bulk_uploads.status')
- if legend && legend_text.present?
  small<= legend_text

app/views/bulk_uploads/edit.html.slim
- set_title t('navigation.bulk_uploads')

= render('jobs_hint')

- if @bulk_upload.importing?
  - info = 'Die Beweisfotos aus dem Album werden im Hintergrund heruntergeladen. Dies kann etwas Zeit in Anspruch nehmen.'
  - note = 'Import läuft'
  = render('components/reload', note: note, info: info)
- elsif @bulk_upload.processing?
  - info = 'Die Beweisfotos im Massen-Upload werden im Hintergrund verarbeitet in verschiedenen Größen, z.B. als Thumbnails, bereitgestellt. Dies kann etwas Zeit in Anspruch nehmen.'
  - note = "Verarbeitung läuft"
  = render('components/reload', note: note, info: info)

- elsif @photos.present?

  - if current_user.autosuggest.zero?
    - message = "Sollen Vorschläge automatisch übernommen werden, können die Auto-Suggest Einstellungen #{link_to('im Profil', edit_user_path)} geändert werden."
    = render('application/flash/alert', type: 'info', message: message)

  .well.well-sm.callout-primary
    | Mehrere Beweisfotos gruppiert nach Vergehen ins obere Feld ziehen, oder mit Hilfe des
    span.glyphicon.glyphicon-move<>
    | Button dorthin bewegen und anschließend eine neue Meldung anlegen.

  = form_with model: @bulk_upload do |form|
    = hidden_field_tag :order_column, @order_column
    = hidden_field_tag :order_direction, @order_direction
    .row
      .col-lg-12
        fieldset Beweisfotos für neue Meldung
    .row
      .col-lg-8
        = render 'photo_list', bulk_upload: @bulk_upload, photos: [@photos.first]
      .col-lg-4
        p
          = form.button type: :submit, class: "btn btn-success btn-block"
            span.glyphicon.glyphicon-plus>
            | neue Meldung anlegen
        .well
          p
            = link_to url_for(params.to_unsafe_hash), class: "btn btn-sm btn-default btn-block"
              span.glyphicon.glyphicon-refresh>
              | Beweisfotos aktualisieren

          button type="button" class="btn btn-default btn-sm btn-block dropdown-toggle" data-toggle="dropdown" aria-expanded="false"
            | sortiert #{@order_direction == 'asc' ? '⬆' : '⬇'} #{@order_column == 'filename' ? 'nach Dateinamen' : 'wie hochgeladen'} <span class="caret"></span>
          ul.dropdown-menu
            li
              = link_to '⬆ nach Dateinamen', url_for(order_column: 'filename', order_direction: 'asc')
              = link_to '⬇ nach Dateinamen', url_for(order_column: 'filename', order_direction: 'desc')
              = link_to '⬆ wie hochgeladen', url_for(order_column: 'created_at', order_direction: 'asc')
              = link_to '⬇ wie hochgeladen', url_for(order_column: 'created_at', order_direction: 'desc')

  .row
    .col-lg-12
      fieldset Verbleibende Beweisfotos
  .row
    .col-lg-12
      = render 'photo_list', bulk_upload: @bulk_upload, photos: @photos - [@photos.first]

  javascript:
    function ziehen(ev) {
      ev.dataTransfer.setData('text', ev.target.id);
    }

    function ablegenErlauben(ev, el) {
      ev.preventDefault();
      el.classList.add('well-active');
    }

    function ablegenLeave(ev, el) {
      el.classList.remove('well-active');
    }

    function ablegenEnter(ev, el) {
    }

    function ablegen(ev, el) {
      el.classList.remove('well-active');
      ev.preventDefault();
      var data = ev.dataTransfer.getData('text');
      el.children[0]?.appendChild(document.getElementById(data));
    }

    function ablegenMove(id) {
      const el = document.getElementById(id);
      const first = document.getElementsByClassName('droppable-list')[0];
      const last = document.getElementsByClassName('droppable-list')[1];
      if (Array.from(first.childNodes).includes(el)) {
        last?.appendChild(el);
      } else {
        first?.appendChild(el);
      }
    }

  hr.spacer

  .row
    .col-lg-3
      = form_with model: @bulk_upload do |form|
        = form.submit 'Pro Beweisfoto eine neue Meldung', name: 'one_per_photo', class: "btn btn-primary btn-block"
    .col-lg-9
      .well.well-sm.callout-primary Sollte jedes Beweisfoto zu einem eigenen Vergehen gehören, dann hier pro Beweisfoto jeweils eine neue Meldung erzeugen.

  - if @bulk_upload.notices.present?
    hr.spacer

    .panel.panel-default
      = render 'notice_list', notices: @bulk_upload.notices

- else
  - if @bulk_upload.error?
    .well.well-sm.callout-danger
      small= @bulk_upload.error_message
  - else
    .well.well-sm.callout-primary Alle Beweisfotos wurden bereits zugeordnet und in neue Meldungen überführt.

    .panel.panel-default
      = render 'notice_list', notices: @bulk_upload.notices

app/views/bulk_uploads/index.html.slim
- set_title t('navigation.bulk_uploads')

= render('jobs_hint')

= form_tag bulk_bulk_uploads_path, method: :post do
  .panel.panel-default
    .panel-heading
      .row
        .col-xs-8
          = link_to new_bulk_upload_path, class: 'btn btn-sm btn-success', title: 'Massen-Upload starten'
            span.glyphicon.glyphicon-cloud-upload
        .col-xs-4.text-right
          = link_to bulk_uploads_path, class: 'btn btn-sm btn-default', title: 'Filter zurücksetzen'
            span.glyphicon.glyphicon-remove

    .table-responsive.table-padding
      table.table.table-striped.table-hover
        thead
          tr
            th
            th= BulkUpload.human_attribute_name(:photos)
            th
              => BulkUpload.human_attribute_name(:created_at)
              - if params.dig(:order, :column) == 'created_at'
                - if params.dig(:order, :value) == 'ASC'
                  = link_to url_for(@table_params.deep_merge(order: {column: :created_at, value: 'DESC'}))
                    span.glyphicon.glyphicon-arrow-up.smaller
                - else
                  = link_to url_for(@table_params.deep_merge(order: {column: :created_at, value: 'ASC'}))
                    span.glyphicon.glyphicon-arrow-down.smaller
                = link_to url_for(@table_params.merge(order: {}))
                  span.text-muted.glyphicon.glyphicon-remove.smaller
              - else
                = link_to url_for(@table_params.deep_merge(order: {column: :created_at, value: 'ASC'}))
                  span.glyphicon.glyphicon-arrow-up.smaller.text-muted
            th
              .dropdown
                button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                  => params[:filter] ? BulkUpload.human_attribute_name(params[:filter][:status]) : BulkUpload.human_attribute_name(:status)
                  span.caret
                ul.dropdown-menu aria-labelledby="dropdownMenu1"
                  - BulkUpload.statuses.keys.each do |status|
                    li
                      = link_to url_for(@table_params.merge(filter: {status: status})) do
                        = render 'bulk_upload_status', status: status
                  li role="separator" class="divider"
                  li= link_to 'kein Filter', url_for(@table_params.merge(filter: nil))

        tbody
          - if @bulk_uploads.present?
            - @bulk_uploads.each do |bulk_upload|
              tr
                td
                  label.btn-sm
                    = check_box_tag "selected[]", bulk_upload.id, false, class: 'select-all checkbox-addon'
                  .btn-group.dropdown
                    = render 'bulk_upload_actions', bulk_upload: bulk_upload
                td
                  - if bulk_upload.photos.present?
                    = link_to([:edit, bulk_upload]) do
                      - bulk_upload.photos.first(3).each do |photo|
                        = image_tag(url_for_photo(photo, size: :preview), class: 'index-photo')
                  - else
                    = link_to('-', [:edit, bulk_upload])
                td= d(bulk_upload.created_at)
                td= render 'bulk_upload_status', status: bulk_upload.status

          - else
            tr
              td(colspan=7) Es wurden keine Uploads gefunden
    .panel-footer
      .btn-group.btn-group-checkbox.dropup
        label.btn.btn-sm
          .hidden= check_box_tag :select_all, '', false, onchange: "$('.select-all').prop('checked', $(this).prop('checked'))"
          | alle auswählen

        button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Aktionen"
          span.glyphicon.glyphicon-tasks<>
          span.caret

        ul.dropdown-menu
          li
            = button_tag name: :bulk_action, value: :destroy, type: :submit, class: 'btn btn-sm btn-link', data: {confirm: 'Die Massen-Uploads werden endgültig gelöscht'}
              span.glyphicon.glyphicon-trash>
              span Auswahl löschen

.text-center
  = paginate @bulk_uploads


dl.dl-horizontal.well
  - BulkUpload.statuses.keys.each do |status|
    dt= render 'bulk_upload_status', status: status
    dd= t(status, scope: 'bulk_uploads.status-hints', default: '')

app/views/bulk_uploads/new.html.slim
- set_title t('navigation.bulk_uploads')

= form_errors @bulk_upload

.bs-component
  ul.nav.nav-tabs.nav-panel
    li.active = link_to 'Fotos hochladen', "#upload", data: { toggle: "tab" }
    li = link_to 'Google Album importieren', "#import", data: { toggle: "tab" }

  .tab-content
    .tab-pane.fade.active.in#upload
      .panel.panel-default.panel-nav
        .panel-body
          = form_for @bulk_upload do |form|
            = render 'components/photos_form', form: form, required: true, description: t('bulk_uploads.steps.photos.description')

            .row
              .col-lg-12
                .pull-right
                  .btn-group
                    = form.submit 'Hochladen & Zuordnen', class: "btn btn-success"

    .tab-pane.fade.in#import
      .panel.panel-default.panel-nav
        .panel-body
          .well.well-sm.callout-primary Massen-Uploads via Google-Photos sind derzeit wieder in BETA verfügbar!
          = form_for @bulk_upload, url: import_bulk_uploads_path, method: :post do |form|
            .row
              .col-lg-12
                = form.label :shared_album_url, 'Google-Photos Album', class: "control-label control-label-required"
                = form.url_field :shared_album_url, class: "form-control", required: true, placeholder: 'z.B. https://photos.app.goo.gl/X4KX7AXNjXXu69Uf9'

            hr

            .row
              .col-lg-12
                .pull-right
                  .btn-group
                    = form.submit "Importieren & Zuordnen", class: "btn btn-success"