config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new

  resources :apidocs, only: [:index]

  namespace :admin do
    resources :system, only: [:index]
    resources :users do
      get :login
      patch :merge
    end
    resources :exports
    resources :data_sets
    resources :districts do
      collection do
        get :bulk
        post :bulk_update
      end
    end
    resources :notices do
      post :analyze
    end
    resources :bulk_uploads
    resources :replies
    resources :snippets
    resources :charges
    resources :charge_variants
    resources :authorizations

    get :system, to: "system#index", as: :system_status
    root to: "users#index"
  end

  namespace :api, constraints: { format: :json } do
    resources :notices do
      member { patch :mail }
    end
    resources :uploads, only: [:create]
  end

  resources :replies
  resources :snippets

  resources :bulk_uploads do
    member { patch :purge }

    collection do
      post :bulk
      post :import
    end
  end

  resources :notices do
    member do
      get :inspect
      get :colors
      get :share
      get :suggest
      get :pdf
      get :retrieve
      patch :forward
      patch :status
      patch :duplicate
      patch :mail
      patch :enable
      patch :disable
      patch :analyze
      patch :purge
      patch :upload
    end

    collection do
      get :dump
      get :stats
      get :map
      post :geocode
      post :bulk
      post :import
    end
  end

  resource :user, except: %i[create new index] do
    member do
      get :studi
      post :generate_export
      patch :confirmation_mail
      patch :signature
      patch :destroy_signature
    end
  end
  # https://github.com/rails/rails/issues/1769#issuecomment-301643924
  resolve("User") { [:user] }

  resources :districts do
    member { get :wegeheld }
  end

  resources :charges, only: %i[index show] do
    collection { get :list }
  end
  resources :exports, only: :index
  resource :sitemap, only: :show

  scope "/p" do
    get "/charge/:token", to: "public#charge", as: :public_charge
    get "/profile/:token", to: "public#profile", as: :public_profile
    get "/winowig/:user_token/:notice_token",
        to: "public#winowig",
        as: :public_winowig,
        defaults: {
          format: :xml,
        }
  end

  scope "/auth" do
    unless Rails.env.production?
      get "/offline_login/:nickname", to: "sessions#offline_login"
    end
    get "/:provider/callback", to: "sessions#create", as: :provider_callback
    delete "/:provider", to: "sessions#disconnect"
    get "/failure", to: "sessions#failure"
    get "/destroy_alias_session",
        to: "sessions#destroy_alias",
        as: :logout_alias
    get "/destroy_session", to: "sessions#destroy", as: :logout
    get "/validation/:token", to: "sessions#validation", as: :validation
    get "/signup", to: "sessions#signup", as: :signup
    get "/ticket", to: "sessions#ticket", as: :ticket
    get "/login", to: "sessions#login", as: :login
    get "/email", to: "sessions#email", as: :email_login
    post "/complete", to: "sessions#complete", as: :complete
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_signup", to: "sessions#email_signup", as: :email_signup
  end

  root "home#index"

  get "/home", to: "home#index", as: :home
  get "/wegeheld", to: "home#wegeheld", as: :wegeheld
  get "/generator", to: "home#generator", as: :generator
  get "/imprint", to: "home#imprint", as: :imprint
  get "/map", to: "home#map", as: :map
  get "/leaderboard", to: "home#leaderboard", as: :leaderboard
  get "/stats", to: "home#stats", as: :stats
  get "/features", to: "home#features", as: :features
  get "/faq", to: "home#faq", as: :faq
  get "/api", to: "home#api", as: :api
  get "/violation", to: "home#violation", as: :violation
  get "/privacy", to: "home#privacy", as: :privacy
  get "/donate", to: "home#donate", as: :donate
  get "/year", to: "home#year", as: :year
  get "/year2022" => redirect("/year?year=2022")
  get "/year2021" => redirect("/year?year=2021")
  get "/year2020" => redirect("/year?year=2020")
  get "/year2019" => redirect("/year?year=2019")

  if Rails.env.development?
    get "/cdn-cgi/image/width=:width,height=:height,fit=:fit,quality=:quality/storage/:key.:extension",
        to: "styleguide#photo"
  end

  get "/styleguide", to: "styleguide#index"

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/ping",
      to: ->(env) { [200, { "Content-Type" => "text/html" }, ["pong"]] }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Statisticable
  include Bitfields

  bitfield :flags,
           1 => :hide_public_profile,
           2 => :disable_reminders,
           4 => :disable_autoreply_notifications

  bitfield :autosuggest,
           1 => :from_exif,
           2 => :from_proximity,
           4 => :from_recognition,
           8 => :from_history

  enum access: { disabled: -99, user: 0, community: 1, studi: 2, admin: 42 }

  geocoded_by :geocode_address,
              language: proc { |_model| I18n.locale },
              no_annotations: true
  after_validation :geocode, if: :geocode_address_changed?
  after_validation :normalize
  before_validation :defaults

  belongs_to :district, optional: true, foreign_key: :zip, primary_key: :zip
  has_many :bulk_uploads, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :notices, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :replies, -> { order(created_at: :desc) }, through: :notices
  has_many :snippets, -> { order(:priority, [created_at: :desc]) }
  has_many :authorizations, dependent: :destroy
  has_many :photos_attachments, through: :notices

  has_one_attached :signature

  accepts_nested_attributes_for :authorizations

  validates :nickname,
            :email,
            :token,
            :name,
            :street,
            :zip,
            :city,
            presence: true
  validates :email, :token, uniqueness: true
  validates :email,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
            }
  validate :email_block_list

  def email_block_list
    if email =~ /miucce.com/ || email =~ /spamgourmet.com/
      errors.add(:email, :invalid)
    end
  end

  scope :last_login_since, ->(date) { where("last_login > ?", date) }
  scope :since, ->(date) { where("created_at > ?", date) }
  scope :for_public, -> { not_hide_public_profile }
  scope :active, -> { where("access >= 0") }

  def self.from_param(token)
    find_by!(token:)
  end

  def to_param
    token
  end

  def merge(source)
    User.transaction do
      source.notices.update_all(user_id: id)
      source.bulk_uploads.update_all(user_id: id)
    end
  end

  def favorite_tbnrs(max: 25)
    @favorite_tbnrs ||= notices.since(6.month.ago).reorder(nil).distinct(:tbnr).limit(max).pluck(:tbnr)

    (@favorite_tbnrs + Charge::FAVS).first(max)
  end

  def validate!
    auth = authorizations.find_or_initialize_by(provider: "email")
    auth.update! uid: email_uid

    update! validation_date: Time.now
  end

  def email_uid
    Digest::SHA256.new.hexdigest(email)
  end

  def validated?
    validation_date.present?
  end

  def geocode_address
    "#{street}, #{zip}, #{city}, Deutschland"
  end

  def geocode_address_changed?
    street_changed? || zip_changed? || city_changed?
  end

  def full_address
    "#{"#{appendix}, " if appendix.present?}#{street}, #{zip} #{city}"
  end

  def first_name
    name[/(\S+)\s+(\S+)/, 1]
  end

  def last_name
    name[/(\S+)\s+(\S+)/, 2] || name
  end

  def street_without_housenumber
    street.gsub(/(.+) (\d+\w?)$/, '\1')
  end

  def housenumber
    street.gsub(/(.+) (\d+\w?)$/, '\2')
  end

  def to_label
    "#{nickname} (#{email})"
  end

  def public_nickname
    hide_public_profile? ? "Anonymous #{nickname.first.upcase}" : nickname
  end

  def wegli_email
    "#{token}@anzeige.weg.li"
  end

  def coordinates?
    latitude? && longitude?
  end

  def map_data
    { latitude:, longitude: }
  end

  def statistics
    {
      notices: notices.count,
      incomplete: notices.incomplete.count,
      open: notices.open.count,
      shared: notices.shared.count,
    }
  end

  def leaderboard_positions
    daily =
      Notice
        .shared
        .since(Time.zone.now.beginning_of_day)
        .group(:user_id)
        .order(count_all: :desc)
        .count
    weekly =
      Notice
        .shared
        .since(Time.zone.now.beginning_of_week)
        .group(:user_id)
        .order(count_all: :desc)
        .count
    monthly =
      Notice
        .shared
        .since(Time.zone.now.beginning_of_month)
        .group(:user_id)
        .order(count_all: :desc)
        .count
    yearly =
      Notice
        .shared
        .since(Time.zone.now.beginning_of_year)
        .group(:user_id)
        .order(count_all: :desc)
        .count
    alltime = Notice.group(:user_id).order(count_all: :desc).count

    @positions = [
      [
        "daily",
        daily.keys.index(id).to_i,
        daily[id].to_i,
        daily.first&.last.to_i,
      ],
      [
        "weekly",
        weekly.keys.index(id).to_i,
        weekly[id].to_i,
        weekly.first&.last.to_i,
      ],
      [
        "monthly",
        monthly.keys.index(id).to_i,
        monthly[id].to_i,
        monthly.first&.last.to_i,
      ],
      [
        "yearly",
        yearly.keys.index(id).to_i,
        yearly[id].to_i,
        yearly.first&.last.to_i,
      ],
      [
        "alltime",
        alltime.keys.index(id).to_i,
        alltime[id].to_i,
        alltime.first&.last.to_i,
      ],
    ]
  end

  private

  def normalize
    self.email = email.to_s.downcase
  end

  def defaults
    self.token ||= SecureRandom.hex(16)
    self.api_token ||= SecureRandom.hex(32)
  end

  class << self
    def authenticated_with_token(id, stored_token)
      user = find_by_id(id)
      user && user.token == stored_token ? user : nil
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    def login
      user = User.from_param(params[:user_id])
      sign_in_alias(user)

      redirect_to root_path, notice: "Signed in as #{user.name}"
    end

    def merge
      user = User.from_param(params[:user_id])
      source = User.find(params[:source_id])
      user.merge(source)

      redirect_to [:admin, user], notice: "Merged data from #{source.id}"
    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate!
  before_action :authenticate_studi_user!, only: %i[studi generate_export]

  def show
    @since = (params[:since] || 4).to_i
    @display = %w[cluster heat multi].delete(params[:display]) || "cluster"
    @notices = current_user.notices.shared.since(@since.weeks.ago)
    @positions = current_user.leaderboard_positions
  end

  def edit; end

  def signature
    current_user.update!(signature_params)

    redirect_to edit_user_path, notice: "Unterschrift wurde gespeichert"
  end

  def destroy_signature
    current_user.update!(signature: nil)

    redirect_to edit_user_path, notice: "Unterschrift wurde entfernt"
  end

  def update
    current_user.assign_attributes(user_params)

    if current_user.email_changed?
      current_user.validation_date = nil
      if current_user.save
        UserMailer.validate(current_user).deliver_later
        redirect_to edit_user_path,
                    notice: t("users.profile_updated_and_confirmation_email")
      else
        redirect_to edit_user_path,
                    alert: current_user.errors.full_messages.to_sentence
      end
    else
      current_user.save!

      redirect_to edit_user_path, notice: t("users.profile_updated")
    end
  end

  def confirmation_mail
    UserMailer.validate(current_user).deliver_later

    redirect_to edit_user_path,
                notice: t("users.confirmation_mail", email: current_user.email)
  end

  def studi
    @exports = Export.for_studis
  end

  def generate_export
    export_type = params[:export][:export_type] || :photos
    interval = params[:export][:interval] || Date.today.cweek
    Rails.logger.info(
      "create export for type #{export_type} in week #{interval}",
    )

    Scheduled::ExportJob.perform_later(export_type:, interval:)
    redirect_to studi_user_path,
                notice:
                  "Export #{export_type}/#{interval} wurde gestartet, es kann einige Minuten Dauern bis dieser hier erscheint."
  end

  def destroy
    current_user.destroy!
    sign_out

    redirect_to root_path, notice: t("users.destroyed")
  end

  private

  def signature_params
    params.require(:user).permit(:signature)
  end

  def user_params
    params.require(:user).permit(
      %i[email nickname name street zip city appendix date_of_birth phone] +
        User.bitfields[:flags].keys + User.bitfields[:autosuggest].keys,
    )
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar(user)
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email.strip.downcase)}",
              alt: user.name,
              title: user.name,
              class: "gravatar"
  end
end

app/views/users/_api_token.html.slim
.panel.panel-default
  .panel-heading API-Token ⚡️
  .panel-body
    = text_field_tag(:api_token, current_user.api_token, disabled: true, class: "form-control")
    = button_tag class: "btn btn-default btn-block", onclick: "event.preventDefault(); window.prompt('#{t('notices.copy_hint')}', '#{current_user.api_token}')" do
      span.glyphicon.glyphicon-list-alt>
      span API-Token kopieren
  .panel-footer
    | Schema und Beispiele können Entwickler in der #{link_to 'API-Documentation', '/api-docs', target: '_blank'} nachschauen.

app/views/users/edit.html.slim
- set_title t('navigation.profile')

.row
  .col-lg-6
    = form_for current_user, html: {class: "form-horizontal"} do |form|
      .panel.panel-default
        .panel-heading Persönliche Daten 👤
        .panel-body
          = form.label :name, class: "control-label control-label-required"
          = form.text_field :name, class: "form-control", required: true, placeholder: 'z.B. Hanno Nym'
            = hint do
              | Vollständiger Name und ladungsfähige Adresse werden als Zeugendaten benötigt.

          = form.label :street, class: "control-label control-label-required"
          = form.text_field :street, class: "form-control", required: true, placeholder: 'z.B. Sylvesterallee 7'

          = form.label :city, class: "control-label control-label-required"
          = form.text_field :city, class: "form-control", required: true, placeholder: 'z.B. Hamburg'

          = form.label :zip, class: "control-label control-label-required"
          = form.text_field :zip, class: "form-control", required: true, placeholder: 'z.B. 22525'

          = form.label :appendix, class: "control-label"
          = form.text_field :appendix, class: "form-control", placeholder: 'z.B. c/o Kühne GmbH'
          = hint do
            | Als ladungsfähige Adresse kann auch z.B. die des Arbeitgebers genutzt werden.

          = form.label :date_of_birth, class: "control-label"
          = form.date_field :date_of_birth, class: "form-control", placeholder: 'z.B. 28.09.1991'
          = hint do
            | Ist ein Geburtsdatum vorhanden, dann wird dieses in der Anzeige angegeben.

          = form.label :phone, class: "control-label"
          = form.text_field :phone, class: "form-control", placeholder: 'z.B. 040 600 90 76 98'
          = hint do
            | Ist eine Telefonnummer vorhanden, dann wird diese für Rückfragen mit angegeben.

        .panel-footer.clearfix
          .pull-right
            = form.submit "speichern", class: "btn btn-success"


    .panel.panel-default
      .panel-heading E-Mail Adresse 💌

      .panel-body
        = form_for current_user do |form|
          .input-group
            = form.email_field :email, class: 'form-control', required: true
            span.input-group-btn
              = form.submit t('users.change_email'), class: "btn btn-default"
          = hint do
            | Nach dem Ändern der E-Mail Adresse muss diese anschließend bestätigt werden.
      .panel-body
        - if current_user.validated?
          = link_to "#", class: "btn btn-default btn-block disabled"
            span>= t('users.email_confirmed')
            span.glyphicon.glyphicon-ok
        - else
          = button_to t('users.confirm_email'), confirmation_mail_user_path(current_user), method: :patch, class: "btn btn-primary btn-block"

    a.anchor#signature Signature Anchor
    = form_for current_user, url: signature_user_path, html: {class: "form-horizontal"} do |form|
      .panel.panel-default
        .panel-heading Unterschrift 🖋
        - if current_user.signature.present?
          .panel-body
            = image_tag url_for(current_user.signature), class: 'signature'
          .panel-body
            = link_to destroy_signature_user_path(current_user), method: :patch, data: {confirm: 'Die Unterschrift wirklich entfernen?'}, class: "btn btn-default btn-block"
              span.glyphicon.glyphicon-trash>
              span Unterschrift entfernen
        .panel-body
          = form.file_field :signature, id: 'fileupload', required: true, direct_upload: true, class: "form-control-file input-droppable", accept: 'image/jpeg'
          = hint do
            | Die Unterschrift im JPEG Format wird für die Generierung von Anzeigen als PDF genutzt.

        .panel-footer.clearfix
          .pull-right
            = form.submit "hochladen", class: "btn btn-success"

  .col-lg-6
    = form_for current_user, html: {class: "form-horizontal"} do |form|
      .panel.panel-default
        .panel-heading Einstellungen ⚙️
        .panel-body
          = form.label :nickname, class: "control-label control-label-required"
          = form.text_field :nickname, class: "form-control", required: true
          = hint do
            | Der Spitzname wird im öffentlichen Profil verwendet.

          - User.bitfields[:flags].keys.each do |key|
              .checkbox
                label
                  = form.check_box key
                  = t("users.flags.#{key}")

        .panel-footer.clearfix
          .pull-right
            = form.submit "speichern", class: "btn btn-success"

  .col-lg-6
    = form_for current_user, html: {class: "form-horizontal"} do |form|
      .panel.panel-default
        .panel-heading Auto-Suggest 🤖
        .panel-body
          = hint do
            | Vorschläge nach der Analyse der Beweisfotos automatisch in die Anzeige übernehmen:

          - User.bitfields[:autosuggest].keys.each do |key|
              .checkbox
                label
                  = form.check_box key
                  = t("users.autosuggest.#{key}")

        .panel-footer.clearfix
          .pull-right
            = form.submit "speichern", class: "btn btn-success"

    .panel.panel-default
      .panel-heading Verknüpfungen 🔐
      .panel-body
        - auths = current_user.authorizations
        - auths.each do |auth|
          p.btn-group
            = link_to "#", class: "btn btn-default disabled"
              span>= ApplicationHelper::PROVIDERS[auth.provider.to_sym]
              span.glyphicon.glyphicon-ok
            - if auths.size > 1
              = link_to("/auth/#{auth.provider}", method: :delete, title: "Verknüpfung entfernen", data: {confirm: 'Die Verknüpfung für den Login wirklich löschen?'}, class: "btn btn-danger")
                span.glyphicon.glyphicon-trash

        - existing_providers = auths.map(&:provider)
        - login_links(ApplicationHelper::PROVIDERS.select {|p| !existing_providers.include?(p.to_s)}) do |name, path, key|
          p = button_to(t('users.connect_via', provider: name), path, {class: "btn btn-default btn-block"})

    = render('api_token')

    .panel.panel-default
      .panel-heading Aktionen 🚨
      .panel-body
        = button_to t('users.delete_account'), user_path(current_user), method: :delete, data: {confirm: 'Den Account und alle Daten wirklich löschen?'}, class: "btn btn-danger btn-block"

app/views/users/show.html.slim
- set_title t('navigation.profile')

.row
  .col-lg-6
    .panel.panel-default
      .panel-heading Infos zum Account
      ul.list-group
        li.list-group-item Mitglied seit: #{l(current_user.created_at.to_date)}
        li.list-group-item Status: #{render('access', access: current_user.access)}

    = render('api_token')

    .panel.panel-default
      .panel-heading Statistik
      ul.list-group
        - current_user.statistics.each do |key, value|
          li.list-group-item
            = t(key, scope: 'notices.statistics')
            .badge.pull-right= value

  .col-lg-6
    = render('components/leaderboard', positions: @positions)

.spacer-large

.well
  | Du hast in den letzten #{@since} Wochen #{@notices.blank? ? 'noch keine' : @notices.size } Anzeigen gegen Falschparker erstattet.

a.anchor#map_filter Map Anchor

ul.nav.nav-tabs.nav-panel
  li(class="#{ 'active' if @display == 'cluster' }")= link_to 'Cluster', url_for(since: @since, display: 'cluster', anchor: :map_filter)
  li(class="#{ 'active' if @display == 'heat' }")= link_to 'Heatmap', url_for(since: @since, display: 'heat', anchor: :map_filter)
  li(class="#{ 'active' if @display == 'multi' }")= link_to 'Karte', url_for(since: @since, display: 'multi', anchor: :map_filter)

.panel.panel-default
  .panel-body.panel-body-map
    = render("components/map/#{@display}", notices: @notices, kind: :private, init: current_user.district&.map_data)

app/views/users/studi.html.slim
h2 👋 Hi Stuids!

h3 GCloud Storage readonly credentials

.well
  pre= (ENV['GOOGLE_READONLY_CREDENTIALS']).as_json

h3 Exports

.table-responsive
  table.table.table-striped.table-hover
    thead
      tr
        th= Export.human_attribute_name(:created_at)
        th= Export.human_attribute_name(:export_type)
        th= Export.human_attribute_name(:interval)
        th= Export.human_attribute_name(:archive)
        th
    tbody
      - @exports.each do |export|
        tr
          td= d(export.created_at)
          td= export.translate_enum(:export_type)
          td= export.interval
          td= "#{export.archive&.filename} / #{number_to_human_size(export.archive&.byte_size)}"
          td
            - if export.archive.present?
              = link_to(rails_blob_path(export.archive, disposition: "attachment"), class: 'btn btn-sm btn-default', title: 'herunterladen') do
                span.glyphicon.glyphicon-download>
                | Herunterladen

= form_for(Export.new(interval: Date.today.cweek), url: generate_export_user_path) do |form|
  .well
    .row
      .col-lg-6
        .form-group
          = form.label :export_type, class: "control-label control-label-required"
          = form.select :export_type, [:photos, :profiles].map {|type| [Export.human_enum_name(:export_type, type), type]}, { include_blank: 'Typ Auswählen' }, { class: "form-control", required: true }
      .col-lg-6
        .form-group
          = form.label :interval, class: "control-label control-label-required"
          = form.text_field :interval, class: "form-control", required: true

  .row
    .col-lg-12
      .pull-right
        .btn-group
          = form.submit "Export starten", class: "btn btn-success", data: {confirm: 'Immer nur einen Export zur Zeit starten!'}