config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new

  resources :apidocs, only: [:index]

  namespace :admin do
    resources :system, only: [:index]
    resources :users do
      get :login
      patch :merge
    end
    resources :exports
    resources :data_sets
    resources :districts do
      collection do
        get :bulk
        post :bulk_update
      end
    end
    resources :notices do
      post :analyze
    end
    resources :bulk_uploads
    resources :replies
    resources :snippets
    resources :charges
    resources :charge_variants
    resources :authorizations

    get :system, to: "system#index", as: :system_status
    root to: "users#index"
  end

  namespace :api, constraints: { format: :json } do
    resources :notices do
      member { patch :mail }
    end
    resources :uploads, only: [:create]
  end

  resources :replies
  resources :snippets

  resources :bulk_uploads do
    member { patch :purge }

    collection do
      post :bulk
      post :import
    end
  end

  resources :notices do
    member do
      get :inspect
      get :colors
      get :share
      get :suggest
      get :pdf
      get :retrieve
      patch :forward
      patch :status
      patch :duplicate
      patch :mail
      patch :enable
      patch :disable
      patch :analyze
      patch :purge
      patch :upload
    end

    collection do
      get :dump
      get :stats
      get :map
      post :geocode
      post :bulk
      post :import
    end
  end

  resource :user, except: %i[create new index] do
    member do
      get :studi
      post :generate_export
      patch :confirmation_mail
      patch :signature
      patch :destroy_signature
    end
  end
  # https://github.com/rails/rails/issues/1769#issuecomment-301643924
  resolve("User") { [:user] }

  resources :districts do
    member { get :wegeheld }
  end

  resources :charges, only: %i[index show] do
    collection { get :list }
  end
  resources :exports, only: :index
  resource :sitemap, only: :show

  scope "/p" do
    get "/charge/:token", to: "public#charge", as: :public_charge
    get "/profile/:token", to: "public#profile", as: :public_profile
    get "/winowig/:user_token/:notice_token",
        to: "public#winowig",
        as: :public_winowig,
        defaults: {
          format: :xml,
        }
  end

  scope "/auth" do
    unless Rails.env.production?
      get "/offline_login/:nickname", to: "sessions#offline_login"
    end
    get "/:provider/callback", to: "sessions#create", as: :provider_callback
    delete "/:provider", to: "sessions#disconnect"
    get "/failure", to: "sessions#failure"
    get "/destroy_alias_session",
        to: "sessions#destroy_alias",
        as: :logout_alias
    get "/destroy_session", to: "sessions#destroy", as: :logout
    get "/validation/:token", to: "sessions#validation", as: :validation
    get "/signup", to: "sessions#signup", as: :signup
    get "/ticket", to: "sessions#ticket", as: :ticket
    get "/login", to: "sessions#login", as: :login
    get "/email", to: "sessions#email", as: :email_login
    post "/complete", to: "sessions#complete", as: :complete
  end

  scope "/sessions" do
    get "/email", to: "sessions#email"
    post "/email_signup", to: "sessions#email_signup", as: :email_signup
  end

  root "home#index"

  get "/home", to: "home#index", as: :home
  get "/wegeheld", to: "home#wegeheld", as: :wegeheld
  get "/generator", to: "home#generator", as: :generator
  get "/imprint", to: "home#imprint", as: :imprint
  get "/map", to: "home#map", as: :map
  get "/leaderboard", to: "home#leaderboard", as: :leaderboard
  get "/stats", to: "home#stats", as: :stats
  get "/features", to: "home#features", as: :features
  get "/faq", to: "home#faq", as: :faq
  get "/api", to: "home#api", as: :api
  get "/violation", to: "home#violation", as: :violation
  get "/privacy", to: "home#privacy", as: :privacy
  get "/donate", to: "home#donate", as: :donate
  get "/year", to: "home#year", as: :year
  get "/year2022" => redirect("/year?year=2022")
  get "/year2021" => redirect("/year?year=2021")
  get "/year2020" => redirect("/year?year=2020")
  get "/year2019" => redirect("/year?year=2019")

  if Rails.env.development?
    get "/cdn-cgi/image/width=:width,height=:height,fit=:fit,quality=:quality/storage/:key.:extension",
        to: "styleguide#photo"
  end

  get "/styleguide", to: "styleguide#index"

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"

  get "/ping",
      to: ->(env) { [200, { "Content-Type" => "text/html" }, ["pong"]] }
end

app/models/district.rb
# frozen_string_literal: true

class District < ApplicationRecord
  STATES = %w[
    Baden-Württemberg
    Bayern
    Berlin
    Brandenburg
    Bremen
    Hamburg
    Hessen
    Mecklenburg-Vorpommern
    Niedersachsen
    Nordrhein-Westfalen
    Rheinland-Pfalz
    Saarland
    Sachsen
    Sachsen-Anhalt
    Schleswig-Holstein
    Thüringen
  ]

  include Bitfields
  bitfield :flags, 1 => :personal_email

  enum status: { active: 0, proposed: 1 }
  enum config: { standard: 0, winowig: 1, munich: 2, signature: 3, hamburg: 4 }

  has_many :notices, foreign_key: :zip, primary_key: :zip
  has_many :users, foreign_key: :zip, primary_key: :zip

  validates :name, :zip, :email, :state, presence: true
  validates :zip, uniqueness: true
  validates :zip, format: { with: /\d{5}/ }
  validates :state, inclusion: { in: STATES }
  validates :email,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
            }

  geocoded_by :geocode_address,
              language: proc { |_model| I18n.locale },
              no_annotations: true
  after_validation :geocode, if: :geocode_address_changed?

  acts_as_api

  api_accessible :public_beta do |template|
    %i[
      name
      zip
      email
      prefixes
      latitude
      longitude
      aliases
      personal_email
      created_at
      updated_at
    ].each { |key| template.add(key) }
  end

  api_accessible :wegeheld do |template|
    template.add :id
    template.add :name
    template.add :email
    template.add :zip, as: :postalcode
  end

  def self.from_zip(zip)
    active.find_by(zip:)
  end

  def map_data
    { zoom: 13, latitude:, longitude: }
  end

  def statistics(date = 100.years.ago)
    {
      notices: notices.since(date).count,
      active_users: User.where(id: notices.since(date).pluck(:user_id)).count,
      total_users: users.count,
    }
  end

  def geocode_address
    "#{zip}, #{name}, #{state}, Deutschland"
  end

  def geocode_address_changed?
    zip_changed? || name_changed? || state_changed?
  end

  def all_emails
    aliases.present? ? [email] + aliases : [email]
  end

  def display_name
    "#{zip} #{name}"
  end

  def display_email
    anonymize_email(email)
  end

  def anonymize_email(email)
    return "-" unless email.present?

    return email unless personal_email?

    address, domain = email.split("@")

    "#{address.first}#{'.' * (address.size - 2)}#{address.last}@#{domain}"
  end

  def display_aliases
    return "-" unless aliases.present?

    aliases.map { |email| anonymize_email(email) }.compact.join(", ")
  end

  def self.from_param(param)
    param = param.split("-").first || param
    find_by!(zip: param)
  end

  def to_param
    "#{zip}-#{name.parameterize}"
  end
end

app/controllers/admin/districts_controller.rb
module Admin
  class DistrictsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = BulkUpload.
    #     page(params[:page]).
    #     per(10)
    # end

    def bulk_update
      District.where(email: params[:email]).update_all(
        email: params[:to_email],
        flags: params[:to_flags],
        config: params[:to_config]
      )

      redirect_to admin_districts_path(search: params[:to]),
                  notice:
                    "Bezirke '#{params[:email]}' wurde zu '#{params[:to_email]} #{params[:to_flags]} #{params[:to_config]}' geändert"
    end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   BulkUpload.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def resource_params
      params[:district][:aliases] = params[:district][:aliases].split(
        /;|,|\s/
      ).reject(&:blank?)
      params[:district][:prefixes] = params[:district][:prefixes].split(
        /;|,|\s/
      ).reject(&:blank?)
      params.require(resource_name).permit(
        *dashboard.permitted_attributes,
        aliases: [],
        prefixes: []
      )
    end
  end
end

app/controllers/districts_controller.rb
# frozen_string_literal: true

class DistrictsController < ApplicationController
  include Slack::Slackable

  def index
    respond_to do |format|
      format.html { @districts = search_scope }
      format.json { render json: District.active.as_api_response(:public_beta) }
      format.csv do
        csv_data =
          CSV.generate(force_quotes: true) do |csv|
            csv << %w[plz name email]
            District.in_batches do |relation|
              relation.each do |district|
                csv << [district.zip, district.name, district.email]
              end
            end
          end
        send_data csv_data,
                  type: "text/csv; charset=UTF-8; header=present",
                  disposition:
                    "attachment; filename=districts-#{Time.now.to_i}.csv"
      end
    end
  end

  def show
    @since = (params[:since] || 4).to_i
    @display = %w[cluster heat multi].delete(params[:display]) || "cluster"
    @district = District.active.from_param(params[:id])
    @notices = @district.notices.since(@since.weeks.ago).shared

    respond_to do |format|
      format.html
      format.json { render json: @district.as_api_response(:public_beta) }
    end
  end

  def edit
    @district = District.active.from_param(params[:id])
  end

  def update
    district = District.active.from_param(params[:id])
    district.assign_attributes(district_params)
    changes = district.changes

    if changes.present?
      message =
        changes
          .map { |key, (from, to)| "#{key} changed from #{from} to #{to}" }
          .join(", ")
      notify(
        "district changes proposed: #{message} #{edit_admin_district_url(district)}#{" by #{current_user.email}" if signed_in?}",
      )
    end

    redirect_to(
      districts_path,
      notice: "Änderungen wurden erfasst und warten nun auf Freischaltung",
    )
  end

  def new
    @district = District.new
  end

  def create
    @district = District.new(district_params.merge(status: :proposed))
    if @district.save
      notify(
        "new district proposed: #{edit_admin_district_url(@district)}#{" by #{current_user.email}" if signed_in?}",
      )

      redirect_to(
        districts_path,
        notice: "Bezirk wurde erfasst und wartet nun auf Freischaltung",
      )
    else
      render(:new)
    end
  end

  def wegeheld
    district = District.active.from_param(params[:id])

    respond_to do |format|
      format.json { render json: district.as_api_response(:wegeheld) }
    end
  end

  private

  def district_params
    params[:district][:prefixes] = params[:district][:prefixes].split(
      /;|,|\s/,
    ).reject(&:blank?)
    params.require(:district).permit(
      :name,
      :email,
      :zip,
      :state,
      :osm_id,
      prefixes: [],
    )
  end

  def search_scope
    scope =
      District.active.order(params[:order] || "zip ASC").page(params[:page])
    scope = scope.where("state = ?", params[:state]) if params[:state].present?
    if params[:term].present?
      scope =
        scope.where(
          "zip ILIKE :term OR name ILIKE :term OR email ILIKE :term",
          term: "%#{params[:term]}%",
        )
    end
    scope
  end
end

app/views/districts/_actions.html.slim
- button_text ||= false

.dropdown
  button.btn.btn-default.btn-sm.dropdown-toggle type="button" data-toggle="dropdown"
    | <span class="glyphicon glyphicon-cog"></span>
    =<> 'Aktionen' if button_text
    | <span class="caret"></span>
  ul.dropdown-menu
    li
      = link_to district_path(district)
        span.glyphicon.glyphicon-eye-open>
        | Bezirk ansehen
      = link_to edit_district_path(district)
        span.glyphicon.glyphicon-edit>
        | Bezirk bearbeiten

app/views/districts/_form.html.slim
= form_errors(district)
= form_for(district) do |form|
  .row
    .col-lg-6
      .form-group
        = form.label :name, class: "control-label control-label-required"
        = form.text_field :name, class: "form-control", required: true, placeholder: 'z.B. Hamburg'
        = hint do
          | Der Name der Stadt, Gemeinde oder der Ordnungsbehörde
    .col-lg-6
      .form-group
        = form.label :email, class: "control-label control-label-required"
        = form.email_field :email, class: "form-control", required: true, placeholder: 'z.B. anzeigen@hamburg.de'
        = hint do
          | Offizielle Adresse einer Behörde für Anzeigen in diesem Bezirk
  .row
    .col-lg-6
      .form-group
        = form.label :zip, class: "control-label control-label-required"
        = form.text_field :zip, class: "form-control", required: true, placeholder: 'z.B. 22525', maxlength: 5, pattern: '\d{5}'
    .col-lg-6
      .form-group
        = form.label :state, class: "control-label control-label-required"
        = form.select :state, District::STATES, { include_blank: 'Bundesland Auswählen' }, { class: "form-control", required: true }

  .row
    .col-lg-6
      .form-group
        = form.label :prefixes, class: "control-label"
        = form.text_field :prefixes, class: "form-control", placeholder: 'z.B. HH'
        = hint do
          | Optional die örtlichen Kennzeichen (mit Leerzeichen getrennt)
    .col-lg-6
      .form-group
        = form.label :osm_id, class: "control-label"
        = form.text_field :osm_id, class: "form-control", placeholder: 'z.B. 62782'
        = hint do
          | Optional die OpenStreetmap-ID des Ortes

  .row
    .col-lg-12
      .pull-right
        .btn-group
          = form.submit button_title, class: "btn btn-success"

app/views/districts/_header.html.slim
.page-header
  = link_to districts_path, title: 'Bezirk-Daten' do
    h2.text-primary weg.li Bezirke

app/views/districts/edit.html.slim
- set_title "#{@district.zip} #{@district.name} Änderung vorschlagen"
- set_canonical edit_district_url(@district)

.well.well-sm.callout-primary Die Änderungen für den Bezirk werden vom Support geprüft und dann aktiviert.

= render('form', district: @district, button_title: 'Änderung vorschlagen')

hr.spacer-large

.row
  .col-lg-3
    - subject = "Bezirk aktualisieren: #{@district.zip} #{@district.name} (#{@district.id})"
    - body = "Bitte folgende Änderungen für den Bezirk einspielen:\n\n\nLink für den Support: #{edit_admin_district_url(@district)}"
    = mail_to "peter@weg.li", subject: subject, body: body, class: 'btn btn-block btn-default', title: 'Bezirk ändern'
      | E-Mail schreiben

  .col-lg-9
    .well.well-sm.callout-primary Alternativ kannst Du uns Informationen zu Bezirken auch weiterhin per E-Mail mitteilen.

app/views/districts/index.html.slim
- set_title t('navigation.districts')
- set_meta_description t('meta_description.districts')

.well
  |
    Bei weg.li sind inzwischen #{number_with_delimiter(District.active.count)} Bezirke aus ganz Deutschland hinterlegt. Wir brauchen Deine Hilfe um weitere E-Mail-Adressen der zuständigen Stellen zu recherchieren.

.panel.panel-default
  .panel-heading
    .row
      .col-xs-8
        = link_to(new_district_path, class: 'btn btn-sm btn-success')
          span.glyphicon.glyphicon-plus>
          | Neuen Bezirk erfassen
      .col-xs-4.text-right
        button.btn.btn-default.btn-sm.dropdown-toggle type="button" data-toggle="dropdown"
          | <span class="glyphicon glyphicon-search"></span> Suche <span class="caret"></span>
        ul.dropdown-menu.dropdown-menu-right
          li
            = form_tag({url: url_for}, method: :get, class: 'form-dropdown', autocomplete: :off) do
              .input-group.input-group-sm
                = text_field_tag(:term, params[:term], placeholder: 'z.B. 22525', class: 'form-control input-sm', autofocus: true)
                span.input-group-btn
                  = button_tag(class: "btn btn-default btn-sm")
                    span.glyphicon.glyphicon-search

          - if params[:term].present?
            li.divider
            li
              = link_to url_for
                span.glyphicon.glyphicon-remove>
                | ohne Suche

  .table-responsive
    table.table.table-striped.table-hover
      thead
        tr
          th
          th= District.human_attribute_name(:zip)
          th= District.human_attribute_name(:name)
          th= District.human_attribute_name(:state)
          th= District.human_attribute_name(:email)
          th= District.human_attribute_name(:updated_at)
      tbody
        - if @districts.present?
          - @districts.each do |district|
            tr
              td= render 'actions', district: district
              td= link_to district.zip, district
              td= link_to district.name, district
              td= link_to district.state, district
              td= link_to district.display_email, district
              td= link_to l(district.updated_at, format: :short), district
        - else
          tr
            td(colspan=6) Es wurden keine Einträge gefunden.

.text-center
  = paginate @districts

app/views/districts/new.html.slim
.well.well-sm.callout-primary
  | Der Bezirk wird gespeichert und kann benutzt werden sobald er vom Support aktiviert wurde. Die E-Mail Adresse der zuständigen Stelle ist in der Regel auf der Homepage der Gemeinde zufinden. Sollte dort kein Postfach angegeben sein, sollte irgendeine Kontakt E-Mail Adresse hinterlegt werden.

= render('form', district: @district, button_title: 'Bezirk vorschlagen')

hr.spacer-large

.row
  .col-lg-3
    - body = "Bitte folgenden Bezirk einspielen:\n\nPLZ / Kennzeichen / Name / Bundesland / E-Mail"
    = mail_to "peter@weg.li", subject: "Neuen Bezirk erfassen", body: body, class: 'btn btn-block btn-default', title: 'Bezirk erfassen'
      | E-Mail schreiben

  .col-lg-9
    .well.well-sm.callout-primary Alternativ kannst Du uns Informationen zu Bezirken auch weiterhin per E-Mail mitteilen.

app/views/districts/show.html.slim
- set_title [t('navigation.districts'), @district.zip, @district.name, @district.state].join(' ')
- set_canonical district_url(@district)
- set_meta_description t('meta_description.district', name: @district.name, zip: @district.zip, state: @district.state)

h3= "Bezirk #{@district.zip} #{@district.name} im Bundesland #{@district.state}"

.spacer

.row
  .col-lg-6
    .panel.panel-default
      .panel-heading Infos zum Bezirk
      ul.list-group
        li.list-group-item #{District.human_attribute_name(:zip)}: #{@district.zip}
        li.list-group-item #{District.human_attribute_name(:state)}: #{@district.state}
        li.list-group-item #{District.human_attribute_name(:prefixes)}: #{s(@district.prefixes, default: 'nicht hinterlegt')}
        - if @district.osm_id
          li.list-group-item #{District.human_attribute_name(:osm_id)}: #{link_to(@district.osm_id, "https://www.openstreetmap.org/relation/#{@district.osm_id}", target: '_blank', class: 'external')}
        li.list-group-item.small.text-muted #{District.human_attribute_name(:updated_at)} am #{l(@district.updated_at, format: :date)}

      .panel-footer
        = link_to edit_district_path(@district), class: 'btn btn-default btn-xs'
          span.glyphicon.glyphicon-edit>
          | Bezirk bearbeiten

  .col-lg-6
    .panel.panel-default
      .panel-heading Falschparker-Statistik
      ul.list-group
        - @district.statistics.each do |key, value|
          li.list-group-item
            = t(key, scope: 'districts.statistics')
            .badge.pull-right= value

    .panel.panel-default
      .panel-heading Zuständige Stelle für Anzeigen
      ul.list-group
        li.list-group-item E-Mail-Adresse: #{@district.display_email}
        - if @district.aliases.present?
          li.list-group-item Alternative E-Mail-Adressen: #{@district.display_aliases}
        - if @district.personal_email?
          li.list-group-item.small.text-muted Individualisierte E-Mail-Adressen sind zum Schutz der Personendaten maskiert.

.spacer-lage

.well
  | In #{@district.name} wurden in den letzten #{@since} Wochen #{@notices.blank? ? 'noch keine' : @notices.size } Anzeigen gegen Falschparker erstattet.

= render('components/map/login', notices: @notices, display: @display, since: @since)